<?php

namespace App\Services;

use RuntimeException;

final class ImageSanitizer
{
    private const PNG_SIGNATURE = "\x89PNG\r\n\x1a\n";

    /**
     * Decode an uploaded image and re-encode only its pixel data as PNG.
     *
     * The returned bytes are newly generated by GD and therefore do not
     * preserve EXIF, XMP, IPTC, JPEG comments, PNG text chunks, or the
     * client-supplied filename.
     */
    public function sanitizeToPng(string $sourceBytes): string
    {
        $this->assertGdAvailable();

        if ($sourceBytes === '') {
            throw new RuntimeException('Uploaded image is empty.');
        }

        set_error_handler(
            static function (
                int $severity,
                string $message
            ): bool {
                return true;
            }
        );

        try {
            $image = imagecreatefromstring($sourceBytes);
        } finally {
            restore_error_handler();
        }

        if ($image === false) {
            throw new RuntimeException(
                'Uploaded image could not be decoded safely.'
            );
        }

        /*
         * Preserve alpha information for PNG inputs.
         * This does not introduce metadata and does not perform resizing.
         */
        imagealphablending($image, false);
        imagesavealpha($image, true);

        $bufferLevel = ob_get_level();
        $encoded = false;
        $pngBytes = false;

        ob_start();

        try {
            /*
             * PNG compression is lossless. The compression level affects
             * file size and CPU time only, not decoded pixel values.
             */
            $encoded = imagepng($image, null, 6);
            $pngBytes = ob_get_contents();
        } finally {
            while (ob_get_level() > $bufferLevel) {
                ob_end_clean();
            }

            imagedestroy($image);
        }

        if (
            $encoded !== true
            || ! is_string($pngBytes)
            || $pngBytes === ''
            || ! str_starts_with($pngBytes, self::PNG_SIGNATURE)
        ) {
            throw new RuntimeException(
                'Uploaded image could not be sanitized safely.'
            );
        }

        return $pngBytes;
    }

    private function assertGdAvailable(): void
    {
        if (
            ! extension_loaded('gd')
            || ! function_exists('imagecreatefromstring')
            || ! function_exists('imagepng')
        ) {
            throw new RuntimeException(
                'GD image processing support is unavailable.'
            );
        }
    }
}
